'save_dir': './../../generated_data_v1'
'DATA_SOURCE': './../../Data_Raw'
'DIR': 'us_import1'
'cleaned_csv_subdir': 'cleaned_csv'
'train_data_file': 'train_data.csv'
'test_data_file': 'test_data.csv'
'test_data_file_v1': 'test_data_v1.csv'
'hscode_filter_file_loc': './../../MetaData'
'hscode_filter_file_pattern': '_hs_codes.txt'
'id_col': 'PanjivaRecordID'
'num_jobs': 40
'hscode_col': 'HSCode'
'us_import1':
  'use_cols':
    - 'PanjivaRecordID'
    - 'ConsigneePanjivaID'
    - 'ShipperPanjivaID'
    - 'ShipmentOrigin'
    - 'ShipmentDestination'
    - 'HSCode'
    - 'PortOfUnlading'
    - 'PortOfLading'
    - 'Carrier'
  'num_neg_samples': 10
  'column_value_filters':
    'Carrier':
      - '(Usa))'
  'num_neg_samples_ape': 3
  'low_freq_bound': 3
  'company_domain_columns':
    - 'ShipperPanjivaID'
    - 'ConsigneePanjivaID'

'us_import2':
  'use_cols':
    - 'PanjivaRecordID'
    - 'ConsigneePanjivaID'
    - 'ShipperPanjivaID'
    - 'ShipmentOrigin'
    - 'ShipmentDestination'
    - 'HSCode'
    - 'PortOfUnlading'
    - 'PortOfLading'
    - 'Carrier'
  'num_neg_samples': 10
  'column_value_filters':
    'Carrier':
      - '(Usa))'
  'num_neg_samples_ape': 3
  'low_freq_bound': 5
  'company_domain_columns':
    - 'ShipperPanjivaID'
    - 'ConsigneePanjivaID'

'us_import3':
  'use_cols':
    - 'PanjivaRecordID'
    - 'ConsigneePanjivaID'
    - 'ShipperPanjivaID'
    - 'ShipmentOrigin'
    - 'ShipmentDestination'
    - 'HSCode'
    - 'PortOfUnlading'
    - 'PortOfLading'
    - 'Carrier'
  'num_neg_samples': 10
  'column_value_filters':
    'Carrier':
      - '(Usa))'
  'num_neg_samples_ape': 3
  'low_freq_bound': 10
  'company_domain_columns':
    - 'ShipperPanjivaID'
    - 'ConsigneePanjivaID'

'us_import4':
  'use_cols':
    - 'PanjivaRecordID'
    - 'ConsigneePanjivaID'
    - 'ShipperPanjivaID'
    - 'ShipmentOrigin'
    - 'ShipmentDestination'
    - 'HSCode'
    - 'PortOfUnlading'
    - 'PortOfLading'
    - 'Carrier'
  'num_neg_samples': 4
  'column_value_filters':
    'Carrier':
      - '(Usa))'
  'num_neg_samples_ape': 3
  'low_freq_bound': 5
  'company_domain_columns':
    - 'ShipperPanjivaID'
    - 'ConsigneePanjivaID'

'us_import5':
  'use_cols':
    - 'PanjivaRecordID'
    - 'ConsigneePanjivaID'
    - 'ShipperPanjivaID'
    - 'ShipmentOrigin'
    - 'ShipmentDestination'
    - 'HSCode'
    - 'PortOfUnlading'
    - 'PortOfLading'
    - 'Carrier'
  'num_neg_samples': 4
  'column_value_filters':
    'Carrier':
      - '(Usa))'
  'num_neg_samples_ape': 3
  'low_freq_bound': 5
  'company_domain_columns':
    - 'ShipperPanjivaID'
    - 'ConsigneePanjivaID'

'us_import6':
  'use_cols':
    - 'PanjivaRecordID'
    - 'ConsigneePanjivaID'
    - 'ShipperPanjivaID'
    - 'ShipmentOrigin'
    - 'ShipmentDestination'
    - 'HSCode'
    - 'PortOfUnlading'
    - 'PortOfLading'
    - 'Carrier'
  'num_neg_samples': 4
  'column_value_filters':
    'Carrier':
      - '(Usa))'
  'num_neg_samples_ape': 3
  'low_freq_bound': 5
  'company_domain_columns':
    - 'ShipperPanjivaID'
    - 'ConsigneePanjivaID'